# need secrets:
# - DOCKER_USERNAME
# - DOCKER_TOKEN

name: Release

on:
  push:
    tags:
      - v[0-9]+*

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ichenhe/go-socks5-server
    steps:
      - uses: actions/checkout@v3
      - name: Set tag output
        id: tag_out
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set Release Version
        run: |
          RELEASE_VERSION=${{ steps.tag_out.outputs.tag }}
          echo "RELEASE_VERSION=${RELEASE_VERSION/v/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Build
        run: make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ steps.tag_out.outputs.tag }}
          path: bin
          if-no-files-found: error

      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          # https://github.com/actions/upload-release-asset
          token: ${{ github.token }}
          files: bin/*
          draft: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }},${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
